package DBModel;

public class NoticeDetailBean {

	private String NOTICEDETAIL_ID_PK;
	private String NOTICEDETAIL_SUBTITLE;
	private String NOTICEDETAIL_WRITER;
	private String NOTICEDETAIL_CONTEXT;
	
	public String getNOTICEDETAIL_ID_PK() {
		return NOTICEDETAIL_ID_PK;
	}
	public void setNOTICEDETAIL_ID_PK(String nOTICEDETAIL_ID_PK) {
		NOTICEDETAIL_ID_PK = nOTICEDETAIL_ID_PK;
	}
	public String getNOTICEDETAIL_SUBTITLE() {
		return NOTICEDETAIL_SUBTITLE;
	}
	public void setNOTICEDETAIL_SUBTITLE(String nOTICEDETAIL_SUBTITLE) {
		NOTICEDETAIL_SUBTITLE = nOTICEDETAIL_SUBTITLE;
	}
	public String getNOTICEDETAIL_WRITER() {
		return NOTICEDETAIL_WRITER;
	}
	public void setNOTICEDETAIL_WRITER(String nOTICEDETAIL_WRITER) {
		NOTICEDETAIL_WRITER = nOTICEDETAIL_WRITER;
	}
	public String getNOTICEDETAIL_CONTEXT() {
		return NOTICEDETAIL_CONTEXT;
	}
	public void setNOTICEDETAIL_CONTEXT(String nOTICEDETAIL_CONTEXT) {
		NOTICEDETAIL_CONTEXT = nOTICEDETAIL_CONTEXT;
	}
	
	
}
