package DBModel;

import javafx.scene.control.Button;

public class VideoDetailBean {

	private String VIDEODETAIL_ID_PK;
	private String VIDEODETAIL_SUBTITLE;
	private String VIDEODETAIL_WRITER;
	private String VIDEODETAIL_FILEPATH;
	private Button VIDEODETAIL_BTNDETAIL;
	public String getVIDEODETAIL_ID_PK() {
		return VIDEODETAIL_ID_PK;
	}
	public void setVIDEODETAIL_ID_PK(String vIDEODETAIL_ID_PK) {
		VIDEODETAIL_ID_PK = vIDEODETAIL_ID_PK;
	}
	public String getVIDEODETAIL_SUBTITLE() {
		return VIDEODETAIL_SUBTITLE;
	}
	public void setVIDEODETAIL_SUBTITLE(String vIDEODETAIL_SUBTITLE) {
		VIDEODETAIL_SUBTITLE = vIDEODETAIL_SUBTITLE;
	}
	public String getVIDEODETAIL_WRITER() {
		return VIDEODETAIL_WRITER;
	}
	public void setVIDEODETAIL_WRITER(String vIDEODETAIL_WRITER) {
		VIDEODETAIL_WRITER = vIDEODETAIL_WRITER;
	}
	public String getVIDEODETAIL_FILEPATH() {
		return VIDEODETAIL_FILEPATH;
	}
	public void setVIDEODETAIL_FILEPATH(String vIDEODETAIL_FILEPATH) {
		VIDEODETAIL_FILEPATH = vIDEODETAIL_FILEPATH;
	}
	public Button getVIDEODETAIL_BTNDETAIL() {
		return VIDEODETAIL_BTNDETAIL;
	}
	public void setVIDEODETAIL_BTNDETAIL(Button vIDEODETAIL_BTNDETAIL) {
		VIDEODETAIL_BTNDETAIL = vIDEODETAIL_BTNDETAIL;
	}
	
}
